version: '3'
services:
  web:
    container_name: web-server
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./html:/usr/share/nginx/html # ホストのhtmlディレクトリをマウント
      - ./config:/etc/nginx/conf.d # ホストのconfigディレクトリをマウント
